name = "PowerModelsSecurityConstrained"
uuid = "53333297-f92c-5019-980b-942fc744b407"
authors = ["Carleton Coffrin"]
repo = "https://github.com/lanl-ansi/PowerModelsSecurityConstrained.jl.git"
version = "0.8.2"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Cbc = ">= 0.4"
InfrastructureModels = "~0.6, ~0.7"
Ipopt = ">= 0.4"
JSON = "~0.18, ~0.19, ~0.20, ~0.21"
JuMP = "~0.21, ~0.22"
Memento = "~1.0, ~1.1, ~1.2, ~1.3"
PowerModels = "~0.18, ~0.19"
julia = "^1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Cbc", "Ipopt"]
